import { FlatCompat } from "@eslint/eslintrc";

import { base } from "./base.js";

/**
 * eslint-config-next still ships in eslintrc format, so it has to be
 * bridged into flat config via FlatCompat. `baseDirectory` must be the
 * *consuming app's* directory (not this config package's), so that
 * eslint-config-next's own plugin dependencies resolve correctly through
 * that app's node_modules.
 *
 * @param {string} baseDirectory - pass `import.meta.dirname` from the
 *   app's own eslint.config.js
 * @returns {import("eslint").Linter.Config[]}
 */
export function createNextConfig(baseDirectory) {
  const compat = new FlatCompat({ baseDirectory });

  return [
    ...base,
    ...compat.extends("next/core-web-vitals"),
    {
      // next-env.d.ts is regenerated by Next itself on every `next dev`/
      // `next build` and explicitly says "should not be edited" — its
      // triple-slash references are Next's own convention, not ours to lint.
      ignores: ["next-env.d.ts"],
    },
  ];
}
